Repository DynaPulse/surroundvirtualizer, pull requests merged in 2024-10, with the labels that each got.

#1 Project Initial Setup
  .gitignore
  CMakeLists.txt
  app/main.cpp
  build_script.bat
  include/headers/hrtf_library.h
  include/headers/hrtf_processor.h
  include/headers/openal_setup.h
  include/headers/portaudio_setup.h
  lib/OpenALlibs/bin/OpenAL32.dll
  lib/OpenALlibs/bin/aldebug.exe
  lib/OpenALlibs/bin/allafplay.exe
  lib/OpenALlibs/bin/alrecord.exe
  lib/OpenALlibs/bin/altonegen.exe
  lib/OpenALlibs/bin/openal-info.exe
  lib/OpenALlibs/desktop.ini
  lib/OpenALlibs/include/AL/al.h
  lib/OpenALlibs/include/AL/alc.h
  lib/OpenALlibs/include/AL/alext.h
  lib/OpenALlibs/include/AL/efx-creative.h
  lib/OpenALlibs/include/AL/efx-presets.h
  lib/OpenALlibs/include/AL/efx.h
  lib/OpenALlibs/lib/OpenAL32.lib
  lib/OpenALlibs/lib/cmake/OpenAL/OpenALConfig.cmake
  lib/OpenALlibs/lib/cmake/OpenAL/OpenALTargets-release.cmake
  lib/OpenALlibs/lib/cmake/OpenAL/OpenALTargets.cmake
  lib/OpenALlibs/lib/pkgconfig/openal.pc
  lib/OpenALlibs/share/openal/alsoftrc.sample
  lib/OpenALlibs/share/openal/hrtf/Default HRTF.mhr
  lib/OpenALlibs/share/openal/presets/3D7.1.ambdec
  lib/OpenALlibs/share/openal/presets/hex-quad.ambdec
  lib/OpenALlibs/share/openal/presets/hexagon.ambdec
  lib/OpenALlibs/share/openal/presets/itu5.1-nocenter.ambdec
  lib/OpenALlibs/share/openal/presets/itu5.1.ambdec
  lib/OpenALlibs/share/openal/presets/presets.txt
  lib/OpenALlibs/share/openal/presets/rectangle.ambdec
  lib/OpenALlibs/share/openal/presets/square.ambdec
  lib/PortAudioLibs/bin/portaudio_x64.dll
  lib/PortAudioLibs/include/pa_win_ds.h
  lib/PortAudioLibs/include/pa_win_wasapi.h
  lib/PortAudioLibs/include/pa_win_waveformat.h
  lib/PortAudioLibs/include/pa_win_wdmks.h
  lib/PortAudioLibs/include/pa_win_wmme.h
  lib/PortAudioLibs/include/portaudio.h
  lib/PortAudioLibs/lib/cmake/portaudio/portaudioConfig.cmake
  lib/PortAudioLibs/lib/cmake/portaudio/portaudioConfigVersion.cmake
  lib/PortAudioLibs/lib/cmake/portaudio/portaudioTargets-release.cmake
  lib/PortAudioLibs/lib/cmake/portaudio/portaudioTargets.cmake
  lib/PortAudioLibs/lib/pkgconfig/portaudio-2.0.pc
  lib/PortAudioLibs/lib/portaudio_static_x64.lib
  lib/PortAudioLibs/lib/portaudio_x64.lib
  lib/PortAudioLibs/share/doc/portaudio/LICENSE.txt
  lib/PortAudioLibs/share/doc/portaudio/README.md
  src/hrtf_library.cpp
  src/hrtf_processor.cpp
  src/openal_setup.cpp
  src/portaudio_setup.cpp
Labels: Ready for Review

#10 Updated Codebase
  CMakeLists.txt
  HRTF Files/SADIE_D01/SADIE_D01-44100.mhr
  HRTF Files/SADIE_D01/SADIE_D01-48000.mhr
  HRTF Files/SADIE_D01/SADIE_D01-96000.mhr
  HRTF Files/SADIE_D01/SADIE_D01_(Inverted_Y)-44100.mhr
  HRTF Files/SADIE_D01/SADIE_D01_(Inverted_Y)-48000.mhr
  HRTF Files/SADIE_D01/SADIE_D01_(Inverted_Y)-96000.mhr
  HRTF Files/SADIE_D02/SADIE_D02-44100.mhr
  HRTF Files/SADIE_D02/SADIE_D02-48000.mhr
  HRTF Files/SADIE_D02/SADIE_D02-96000.mhr
  HRTF Files/SADIE_D02/SADIE_D02_(Inverted_Y)-44100.mhr
  HRTF Files/SADIE_D02/SADIE_D02_(Inverted_Y)-48000.mhr
  HRTF Files/SADIE_D02/SADIE_D02_(Inverted_Y)-96000.mhr
  app/main.cpp
  build_script.bat
  include/headers/cli_interface.h
  include/headers/hrtf_library.h
  include/headers/hrtf_processor.h
  include/headers/openal_setup.h
  include/headers/portaudio_setup.h
  src/cli_interface.cpp
  src/hrtf_processor.cpp
  src/openal_setup.cpp
  src/portaudio_setup.cpp
Labels: enhancement, Fix

#11 Setting up Repository
  .gitignore
  CMakeLists.txt
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#13 Create SECURITY.md
  SECURITY.md
Labels: documentation
